# Autogenerated wrapper script for cuPDLPx_jll for x86_64-linux-gnu-cuda+13.0
export libcupdlpx

using Zlib_jll
using CompilerSupportLibraries_jll
using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("cuPDLPx")
JLLWrappers.@declare_library_product(libcupdlpx, "libcupdlpx.so")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, CompilerSupportLibraries_jll, CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        libcupdlpx,
        "lib/libcupdlpx.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
